apps/accounts/urls.py
from django.urls import path

app_name = 'accounts'

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.user_profile, name='user_profile'),
]

emailbackend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]

apps/accounts/models.py
from django.db import models

# Create your models here.

apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.TextInput(attrs={'type': 'password'}))

    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'password']

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from .forms import UserForm

# Create your views here.


def home(request):
    template_name = 'home.html'
    context = {}
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save()
            f.set_password(f.password)
            f.save()
            messages.success(request, 'Usuário cadastrado com sucesso.')
            return redirect('accounts:home')
    form = UserForm()
    context['form'] = form
    return render(request, template_name, context)


def user_login(request):
    template_name = 'user_login.html'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:user_profile')
        else:
            print('deu caca')

    return render(request, template_name, {})


@login_required(login_url='/login/')
def user_profile(request):
    template_name = 'user_profile.html'
    return render(request, template_name, {})


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    messages.success(request, 'Você saiu do sistema.')
    return redirect('accounts:home')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Login Via Email</title>
</head>
<body>
    <h1>Cadastro de Usuário</h1>
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
    <form action="." method="post" autocomplete="off">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar conta</button>
        <a href="{% url 'accounts:user_login' %}">Fazer Login</a>
    </form>
</body>
</html>

templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="." method="post" autocomplete="off">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Usuário ou e-mail">
        <input type="password" name="password" placeholder="Senha">
        <button type="submit">Entrar</button>
    </form>
</body>
</html>

templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Área protegida</title>
</head>
<body>
    <h1>Sou uma área super protegida!!! Só para usuários logados!!!!</h1>
    <h2>Usuário que fez login: {{ user.get_full_name|default:user.username }}</h2>
    <a href="{% url 'accounts:user_logout' %}">Fazer Logout</a>
</body>
</html>